main.class=org.apache.derby.drda.NetworkServerControl
app.classpath=lib/derby.jar;lib/derbynet.jar;lib/derbyshared.jar;lib/derbyclient.jar
java-options=-Dderby.system.home=$APPDIR\\data
arguments=start -h localhost -p 1527