connect 'jdbc:derby:data/posdb;user=app;password=app;';

-- Optional cleanup if you want to wipe existing menu data before loading:
-- delete from MENU_ITEM;
-- delete from MENU_GROUP;
-- delete from MENU_CATEGORY;

-- === Categories ============================================================
INSERT INTO MENU_CATEGORY (NAME, VISIBLE, BEVERAGE, MODIFIED_TIME) VALUES ('Food', 1, 0, CURRENT_TIMESTAMP);
INSERT INTO MENU_CATEGORY (NAME, VISIBLE, BEVERAGE, MODIFIED_TIME) VALUES ('Drinks', 1, 1, CURRENT_TIMESTAMP);

-- === Groups under "Food" ===================================================
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Combos w/ Chips', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Family Meal', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Mexican', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Mr Beasley', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'On The Go Meals', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Loaded Fries', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Sandwiches', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Burgers', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Breakfast', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Grills', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Sides', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Food';

-- === Group under "Drinks" ==================================================
INSERT INTO MENU_GROUP (NAME, CATEGORY_ID, VISIBLE, MODIFIED_TIME)
SELECT 'Drinks', ID, 1, CURRENT_TIMESTAMP FROM MENU_CATEGORY WHERE NAME='Drinks';

-- === Items ================================================================
-- Combos
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Junior T-Bone and Chips', 110.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Combos w/ Chips';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Platter for 2', 220.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Combos w/ Chips';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'T-Bone', 160.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Combos w/ Chips';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Ribs and Chips', 170.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Combos w/ Chips';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT '500g Ribs and Chips', 180.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Combos w/ Chips';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Kwagga Combo', 190.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Combos w/ Chips';

-- Family Meal
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Family Meal', 260.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Family Meal';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Kids Meal (Chicken Burger)', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Family Meal';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Kids Meal (Chicken Strips)', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Family Meal';

-- Mexican
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Taco', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Mexican';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT '2 Tacos', 75.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Mexican';

-- Mr Beasley
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Saucy Steak', 99.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Mr Beasley';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Chicken Tikka', 75.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Mr Beasley';

-- On The Go Meals
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT '100g Mutton Burger and Chips', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='On The Go Meals';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT '200g Beef Burger and Chips', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='On The Go Meals';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Strips and Chips', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='On The Go Meals';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT '4 Chicken Wings and Chips', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='On The Go Meals';

-- Loaded Fries
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Loaded Fries (Medium)', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Loaded Fries';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Loaded Fries (Large)', 85.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Loaded Fries';

-- Sandwiches
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Bacon and Cheese', 55.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sandwiches';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Cheese and Tomato', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sandwiches';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Ham and Cheese', 50.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sandwiches';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Egg and Mayo', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sandwiches';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Cheese and Mushroom', 55.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sandwiches';

-- Burgers
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Casbah Famous Burger', 105.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'The Wood Burger', 90.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Southern Fried Chicken Burger', 75.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Chicken Tikka Burger', 80.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Mutton Burger', 90.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Double Beef Cheese Burger', 120.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Classic Meals', 150.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Classic Beef Burger', 85.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Cheese Burger', 95.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Chicken Burger', 90.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Veggie Burger', 80.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Burgers';

-- Breakfast
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'English Breakfast', 65.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Breakfast';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Omelette', 45.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Breakfast';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'French Toast', 38.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Breakfast';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Pancakes', 42.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Breakfast';

-- Grills
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Rump Steak 300g', 165.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Grills';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'T-Bone Steak 400g', 185.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Grills';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'BBQ Chicken', 110.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Grills';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Lamb Chops', 170.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Grills';

-- Sides
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Chips', 25.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sides';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Rice', 20.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sides';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Salad', 25.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sides';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Onion Rings', 25.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Sides';

-- Drinks
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Coke', 18.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Drinks';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Fanta', 18.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Drinks';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Sprite', 18.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Drinks';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Juice', 22.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Drinks';
INSERT INTO MENU_ITEM (NAME, PRICE, VISIBLE, GROUP_ID, MODIFIED_TIME) SELECT 'Water', 15.00, 1, ID, CURRENT_TIMESTAMP FROM MENU_GROUP WHERE NAME='Drinks';

commit;
disconnect;
exit;
